name: redux_remote_devtools
description: Remote DevTools for Redux.dart. This package connects a Dart Redux store to the Remote Devtools Server, allowing the developer to inspect changes to the Redux Store during runtime.
author: Michael Marner <michael@20papercups.net>
homepage: https://github.com/MichaelMarner/dart-redux-remote-devtools
version: 1.0.4
dependencies:
  redux: '>=3.0.0 <5.0.0'
  redux_dev_tools: '>=0.4.0 <1.0.0'
  socketcluster_client: ^0.2.0
dev_dependencies:
  test: ^1.3.0
  mockito: ^3.0.0
  pedantic: ^1.9.0
environment:
  sdk: '>=2.0.0 <3.0.0'
