name: redux_remote_devtools
description: Remote DevTools for Redux.dart. This package connects a Dart Redux store to the Remote Devtools Server, allowing the developer to inspect changes to the Redux Store during runtime.
author: Michael Marner <michael@20papercups.net>
homepage: https://github.com/MichaelMarner/dart-redux-remote-devtools
version: 3.0.0
dependencies:
  redux: ^5.0.0
  redux_dev_tools: ^0.7.0
  socketcluster_client: ^0.3.0
dev_dependencies:
  build_runner: ^1.10.0
  test: ^1.16.8
  mockito: ^5.0.2
  pedantic: ^1.11.0
environment:
  sdk: '>=2.12.0 <3.0.0'
